!
! Zebra configuration saved from vty
!   2026/07/02 23:14:18
!
frr version 8.5.7
frr defaults traditional
!
hostname as-65000-aggregator
!
!
!
!
interface eth0
exit
!
interface lo0
exit
!
interface lo1
exit
!
!
!
!
!
